// Code generated by "stringer -type=Category"; DO NOT EDIT

package abuseipdb

import "fmt"

const (
	_Category_name_0 = "FraudOrderDDoSAttack"
	_Category_name_1 = "OpenProxyWebSpamEmailSpam"
	_Category_name_2 = "PortScan"
	_Category_name_3 = "BruteForceBadWebBotExploitedHostWebAppAttackSSHIoTTargeted"
)

var (
	_Category_index_0 = [...]uint8{0, 10, 20}
	_Category_index_1 = [...]uint8{0, 9, 16, 25}
	_Category_index_2 = [...]uint8{0, 8}
	_Category_index_3 = [...]uint8{0, 10, 19, 32, 44, 47, 58}
)

func (i Category) String() string {
	switch {
	case 3 <= i && i <= 4:
		i -= 3
		return _Category_name_0[_Category_index_0[i]:_Category_index_0[i+1]]
	case 9 <= i && i <= 11:
		i -= 9
		return _Category_name_1[_Category_index_1[i]:_Category_index_1[i+1]]
	case i == 14:
		return _Category_name_2
	case 18 <= i && i <= 23:
		i -= 18
		return _Category_name_3[_Category_index_3[i]:_Category_index_3[i+1]]
	default:
		return fmt.Sprintf("Category(%d)", i)
	}
}
